services:
  code_base:
    build:
      context: ../..
      dockerfile: images/codeBase_MotorcycleClassification/Dockerfile
    image: codebase_motorcycleclassification
    volumes:
      - ai_system:/tmp
    command: >
      sh -c "cp -r /codeBase/ /tmp/ && python3 /tmp/codeBase/App01.py"
volumes:
  ai_system:
    external: true