services:
  activation_base:
    build:
      context: .
      dockerfile: Dockerfile
    image: activationbase_motorcycleclassification
    volumes:
      - ai_system:/tmp
    command: >
      sh -c "rm -rf /tmp/activationBase/ && cp -r /activationBase/ /tmp/"

volumes:
  ai_system:
    external: true
